services:
  translation-server:
    image: zotero/translation-server@sha256:a80abfaaab0d84c8cc4b0ef79e4fde94b391420ee3a1e69d680fc89a18bff115
    ports:
      - "127.0.0.1:1969:1969"
    restart: unless-stopped
